stages:
  - buildCMSSW
  - build
  - runHzz
  - comparisons
  - harvesting
#before_script:
#  - .gitlab-ci/setup_cmssw.sh

baobabs:
  stage: buildCMSSW
  tags: [ cvmfs ]
  script:
  - wget "https://slack.com/api/chat.postMessage?token=$SLACKTOKEN&channel=slackci&text=Hello%20here%20the%20shears%20CI&pretty=1&username=shearsDocker" 
  - wget "https://slack.com/api/chat.postMessage?token=$SLACKTOKEN&channel=slackci&text=testing%20branch%20$CI_COMMIT_REF_NAME%20for%20$GITLAB_USER_NAME&pretty=1&username=shearsDocker" 
  - .gitlab-ci/compile-scram.sh Baobabs
  artifacts:
    paths:
    - shearsCompilated.tar.gz
    expire_in: 20 minutes

pruner:
  stage: build
  tags: [ cvmfs ]
  script: .gitlab-ci/compile.sh Bonzais
  artifacts:
    paths:
    - Bonzais/pruner
    expire_in: 20 minutes

hzz2l2nu:
  stage: build
  tags: [ cvmfs ]
  script:
    - yum -q -y install boost-devel
    - .gitlab-ci/compile.sh HZZ2l2nu
  artifacts:
    paths:
    - HZZ2l2nu/runHZZanalysis 
    expire_in: 20 minutes

runHzzDiMuData:
  stage: runHzz
  tags: [ cvmfs ]
  script:
    - .gitlab-ci/runHwwCode.sh doubleMuData.root doubleMuHistos.root 0
  artifacts:
    paths:
    - HZZ2l2nu/doubleMuHistos.root
    expire_in: 20 minutes

runHzzDiElData:
  stage: runHzz
  tags: [ cvmfs ]
  script:
    - .gitlab-ci/runHwwCode.sh doubleEGData.root doubleElHistos.root 0
  artifacts:
    paths:
    - HZZ2l2nu/doubleElHistos.root
    expire_in: 20 minutes

runHzzDYMC:
  stage: runHzz
  tags: [ cvmfs ]
  script:
    - .gitlab-ci/runHwwCode.sh Bonzai-DYJetsToLL.root DYHistos.root 1
  artifacts:
    paths:
    - HZZ2l2nu/DYHistos.root
    expire_in: 20 minutes

compDiMu:
  stage: comparisons
  tags: [ cvmfs ]
  script:
    - yum -q -y install glibc-headers glibc-devel git gsl-devel freetype-devel libSM libX11-devel libXext-devel make gcc-c++ gcc binutils libXpm-devel libXft-devel boost-devel
    - .gitlab-ci/runComparisons.sh doubleMuHistos
  artifacts:
    paths:
    - HZZ2l2nu/result_doubleMuHistos
    expire_in: 20 minutes

compDiEle:
  stage: comparisons
  tags: [ cvmfs ]
  script:
    - yum -q -y install glibc-headers glibc-devel git gsl-devel freetype-devel libSM libX11-devel libXext-devel make gcc-c++ gcc binutils libXpm-devel libXft-devel boost-devel
    - .gitlab-ci/runComparisons.sh doubleElHistos 
  artifacts:
    paths:
    - HZZ2l2nu/result_doubleElHistos
    expire_in: 20 minutes

compDYMC:
  stage: comparisons
  tags: [ cvmfs ]
  script:
    - yum -q -y install glibc-headers glibc-devel git gsl-devel freetype-devel libSM libX11-devel libXext-devel make gcc-c++ gcc binutils libXpm-devel libXft-devel boost-devel
    - .gitlab-ci/runComparisons.sh DYHistos
  artifacts:
    paths:
    - HZZ2l2nu/result_DYHistos
    expire_in: 20 minutes

getCompResults:
  stage: harvesting
  tags: [ cvmfs ]
  script:
  - wget "https://slack.com/api/chat.postMessage?token=$SLACKTOKEN&channel=slackci&text=tests%20results%20for%20$CI_COMMIT_REF_NAME&pretty=1&username=shearsDocker" 
  - .gitlab-ci/harvest.sh $SLACKTOKEN
  artifacts:
    paths:
    - HZZ2l2nu/allComparisons.tar.gz 
