image: "gitlab-registry.cern.ch/ci-tools/ci-worker:slc6"

stages:
  - build
  - lint

baobabs:
  stage: build
  tags: [ cvmfs, docker ]
  script:
  - .gitlab-ci/compile-scram.sh Baobabs

pruner:
  stage: build
  tags: [ cvmfs, docker ]
  script: .gitlab-ci/compile.sh Bonzais

DYJets:
  stage: build
  tags: [ cvmfs, docker ]
  script:
    - source DYJets/lcg-env.sh
    - cd DYJets
    - cmake .
    - make

DYJets doxygen:
  stage: lint
  tags: [ cvmfs, docker ]
  allow_failure: true
  script:
    - source DYJets/lcg-env.sh
    - cd DYJets
    - doxygen
    - tar -czf doc.tar.gz doc
    - ../.gitlab-ci/upload-tarball.sh doc doc.tar.gz
