#!/bin/bash

if [  $# -lt 1 -o "$1" = -h -o "$1" = --help ]; then
   cat <<EOF
Usage: getlumi JSON_FILE

Calculates processed integrated luminosity from a crab job lumi section report.

EOF
fi

if [ "$1" = -r ]; then
    recorded_only=y
    shift
else
    recorded_only=n
fi

filter(){
    if [ "$recorded_only" = y ]; then
#	tail -n 2 | head -n 1 | awk -F \| '{printf "%f\n", $7/1.e6}'
	#we look for line Summary, then for a line containing totrecorded (in the table header) and we skip
#        one line corresponding to the header separation line:
	awk -F \| '/#Summary/{a=a+1} /totrecorded/{a=a+1} {if(a>=2) a=a+1} {if(a==5) print $6/1.e6}'
    else
	cat
    fi
}
json="$1"

run(){
json="$1"
python <<EOF
import json
jsonFile="$json"
try:
    r = json.load(open(jsonFile))
    r = map(int, r.keys())
except (IOError, ValueError):
    system.stderr.write("\nFailed to read run list from json file %s.\n\n" % jsonFile)
run_min=min(r)
run_max=max(r)
if run_min > 256600 and  run_max < 258200:
    print 2015
elif run_min > 258200:
    print 2016
else:
    print "?"
EOF
}

dataset="`run "$json"`"

if [ "$dataset" = 2015 ]; then
#Normtag of 2015 data Updated on Mar. 31, 16
    normtag=/afs/cern.ch/user/l/lumipro/public/normtag_file/moriond16_normtag.json
elif [ "$dataset" = 2016 ]; then
    normtag=/afs/cern.ch/user/l/lumipro/public/Normtags/normtag_DATACERT.json
else
    echo "Failed to determine data period and normtag file." 1>&2
    exit 1
fi

#python /afs/cern.ch/user/m/marlow/public/lcr2/lcr2.py -i  "$json" | filter

export PATH=$HOME/.local/bin:/afs/cern.ch/cms/lumi/brilconda-1.0.3/bin:$PATH

#check if brilcalc 2.2.0 is already installed...
[ -x $HOME/.local/bin/brilcalc ] && ~/.local/bin/brilcalc --version | grep -q '^2\.2\.0$' 
#... if not, install it:
if [ $? != 0 ]; then
    pip uninstall brilws
    pip install --install-option="--prefix=$HOME/.local" brilws
fi

#brilcalc lumi -i "$json" -n 0.962 | filter
#before Dec. 6, 15:
#brilcalc lumi --normtag /afs/cern.ch/user/c/cmsbril/public/normtag_json/OfflineNormtagV1.json -i "$json"  | filter
#Updated on Dec. 6, 15 to normtag announced in https://hypernews.cern.ch/HyperNews/CMS/get/luminosity/544.html
#brilcalc lumi --normtag /afs/cern.ch/user/l/lumipro/public/normtag_file/OfflineNormtagV2.json -i "$json"  | filter
echo "Using normtag $normtag." 1>&2
brilcalc lumi --normtag  "$normtag" -i "$1"  --without-checkjson | filter


#pip uninstall brilws
