#!/bin/bash

if [  $# -lt 1 -o "$1" = -h -o "$1" = --help ]; then
   cat <<EOF
Usage: getlumi JSON_FILE

Calculates processed integrated luminosity from a crab job lumi section report.
EOF
fi

if [ "$1" = -r ]; then
    recorded_only=y
    shift
else
    recorded_only=n
fi

filter(){
    if [ "$recorded_only" = y ]; then
	tail -n 2 | head -n 1 | awk -F \| '{print $7/1.e6}'
    else
	cat
    fi
}


#python /afs/cern.ch/user/m/marlow/public/lcr2/lcr2.py -i  "$1" | filter

export PATH=$HOME/.local/bin:/afs/cern.ch/cms/lumi/brilconda-1.0.3/bin:$PATH

if [ ! -x $HOME/.local/bin/brilcalc ]; then
    pip install --install-option="--prefix=$HOME/.local" brilws
fi

#brilcalc lumi -i "$1" -n 0.962 | filter
brilcalc lumi --normtag /afs/cern.ch/user/c/cmsbril/public/normtag_json/OfflineNormtagV1.json -i "$1"  | filter

#pip uninstall brilws
