#!/bin/bash

if [ "$1" = -f ]; then
    force=y
    shift
else
    force=n
fi

era="$1"

if [ -z "$era" -o "$era" = -h -o "$era" = --help ]; then
   cat <<EOF
Usage: new-era [-f] era-name

Description: set up Shears ntuple production file directories for a new era (new beam conditions).

Option:

  -f normally the command will stop on error. With this option it will proceed until the end even in case a step failed.

EOF

exit 0
fi

eos(){
    /afs/cern.ch/project/eos/installation/pro/bin/eos.select  "$@"
}

die(){
    echo "$@" 1>&2
    exit 1
}

mkeosdir(){
    for d in "$@"; do
	if eos ls "$d" 1>/dev/null 2>&1; then
	    echo "The $d directory already exists on EOS!" 1>&2
	elif eos mkdir -p "$d"; then
	    echo "The $d directory was created on EOS."
	else
	    echo "Failed to create directory $1 on EOS." 1>&2
	    [ "$force" = y ] || exit 1
	fi
    done
}


mklocaldir(){
    for d in "$@"; do
	if [ -d "$d" ]; then
	    echo "The $d directory already exists!" 1>&2
	elif mkdir -p "$d"; then
	    echo "The $d directory was created."
	else
	    echo "Failed to create directory $1." 1>&2
	    [ "$force" = y ] || exit 1
	fi
    done
}


mkeosdir /store/group/phys_smp/AnalysisFramework/{Baobab,Bonzai}/"$era"/MC/v1/{Catalogs,Ntuple}
mkeosdir /store/group/phys_smp/AnalysisFramework/{Baobab,Bonzai}/"$era"/Data/v1/{Catalogs,Ntuple}
mklocaldir /afs/cern.ch/user/p/pgras/shearsop/work/{baobab-prod,bonzai-prod}/"$era"/{MC,Data}

(for typ in MC Data; do
    d=/afs/cern.ch/user/p/pgras/shearsop/work/{baobab-prod,bonzai-prod}/"$era"/$typ
    cd "$d"
    ln -s ../../shears/ntuple_production/grow_baobabs_cfg.py .
    ln -s ../../shears/ntuple_production/grow_baobabs .
    ./grow_baobabs --catalog /store/group/phys_smp/AnalysisFramework/Baobab/$era/$typ/v1/Catalogs/datasets.txt 
    done
)

cat <<EOF

**********************************************************************

You need to create on EOS the two input dataset catalog files:

- /store/group/phys_smp/AnalysisFramework/Baobab/$era/MC/v1/Catalogs/datasets.txt

- /store/group/phys_smp/AnalysisFramework/Baobab/$era/MC/v1/Catalogs/datasets.txt

**********************************************************************

EOF
