#!/usr/bin/env python
"""
Commmand to launch baobab ntuple production
"""
import argparse
import sys
import re

try:
    from CRABAPI.RawCommand import crabCommand
except ImportError:
    sys.stderr,write("CRAB 3 environment needs to be set before running this script.")
    sys.exit(1)

from httplib import HTTPException
from WMCore.Configuration import Configuration


parser = argparse.ArgumentParser(description='Launch baobab nutple production.')

parser.add_argument('dataset_catalogs', nargs='+',
                    help='Catalog files containing the list of CMS datasets to process')

parser.add_argument('--max-events', type=int, action='store', default=-1,
                    help='Specify maximum number of events to process for each dataset. The default is to process to full dataset.')

parser.add_argument('--events-per-job', type=int, action='store', default = 100000,
                    help='Specify the number of events each job should process')

args = parser.parse_args()

def checkDataSetName(dataset):
    a = dataset.split("/")
    if len(a) != 4:
        sys.stderr.write("Dataset name must contains three part /primary_dataset/conditions/tier")
        return False
    p = re.compile("MINIAOD(|SIM)")
    if not p.match(a[3]):
        sys.stderr.write("Only MINIAOD and MINIOADSIM data tiers are supported.")
        return False
    return True

def getCrabConfig(dataset, unitsPerJob, outDir, maxEvents):
    """Build the crab configuration file."""
#    dataset_tier = dataset.split("/")[3]
#
#    if dataset_tier.find("SIM") > 0:
#        isMC = True
#    else:
#        isMC = False
    config = Configuration()

    config.section_('General')
#----------------------------------------------------------------------

#Request name. Used to identify job batch and to name the result directory    
    config.General.requestName = dataset.split('/')[2]

#Switch for the copy of the results to the storage site.
    config.General.transferOutputs = True

#Whether or not to copy the job log files to the storage site.
    config.General.transferLogs = True

    config.section_('JobType')
#----------------------------------------------------------------------

# CMSS Configuration file
    config.JobType.psetName = 'grow_baobabs_cfg.py'
#    config.JobType.psetName = 'pset.py'

    config.section_('Data')
#----------------------------------------------------------------------
# Name of the dataset to analyze
    config.Data.inputDataset = dataset

# Output directory on the storage site (storage site defined in the Site section)
    config.Data.outLFNDirBase = outDir

#Mode to use to split the task in jobs. 
# for 'Analysis' job type: 'FileBased', 'LumiBased' (recommended for real data), or 'EventAwareLumiBased'
# for 'PrivateMC' job type: 'EventBased'
    config.Data.splitting = 'EventAwareLumiBased'

# Number of units to produce or process
    if maxEvents and maxEvents > 0:
        config.Data.totalUnits = maxEvents

# Number of units (events in case of PrivateMC)  per job
    config.Data.unitsPerJob = unitsPerJob

# Switch for publication of output data to DBS
    config.Data.publication = False

    config.section_('User')
#----------------------------------------------------------------------
    
    config.section_('Site')
#----------------------------------------------------------------------

#A list of sites where the jobs should not run.
    config.Site.blacklist = ['T3_US_UMD', 'T3_TW_NTU_HEP', 'T3_GR_Demokritos', 'T3_GR_IASA', 'T2_GR_Ioannina', 'T3_MX_Cinvestav', 'T3_IT_Napoli', 'T2_DE_RWTH', 'T2_UK_SGrid_RALPP', 'T3_RU_FIAN', 'T2_FI_HIP']
    
#Site where the output should be copied. 
# See https://cmsweb.cern.ch/sitedb/prod/sites/ for the list of site names
    config.Site.storageSite = 'T2_CH_CERN'
    
    return config

def submitJobs(dataset, unitsPerJob, outDir, maxEvents):
    """Submit crab jobs to produce the Baobab ntuple from a provided dataset."""
    crab_config = getCrabConfig(dataset, unitsPerJob, outDir, maxEvents)

    f = open("crab_" + dataset.split("/")[2] + ".py", "w")
    f.write(str(crab_config))
    f.close()

    try:
        res = crabCommand('submit', config = crab_config)
        print res
    except HTTPException, e:
        print e.headers

def main():
    outDirLine = re.compile(r'#\s*output directory[:\s=]+\s*([^\s]+)')
    commentLine = re.compile(r'^\s*^#')
    for dataset_catalog in args.dataset_catalogs:
        try:
            f = open(dataset_catalog)
        except IOError, e:
            print e
            continue
        outDir = None
        for dataset in f:
            m = outDirLine.match(dataset)
            if m and len(m.groups()) > 0:
                outDir = m.groups()[0]
            elif not outDir:
                sys.stderr.write('''Fatal error while processing dataset catalog '%s'.
Output directory line is missing from the input dataset catalog.
The line should be before any dataset name and should have the following format:
# output directory: /store/group/phys_smp/AnalysisFramework/Baobab/.../ntuples.
''' % dataset_catalog)
                break
            #endif not outDir
            dataset=dataset.strip()
            if len(dataset) == 0 or commentLine.match(dataset):
                continue
            if checkDataSetName(dataset):
                submitJobs(dataset, args.events_per_job, outDir, args.max_events)


if __name__ == '__main__':
    main()

