#!/bin/bash

myself="`readlink -f "$0"`"
mybasename="`basename "$myself"`"
mydir="`dirname "$myself"`"

source "$mydir/prodrc"

mailbox="~shearsop/work/.shears-mailbox"

die(){
    echo "$@" 1>&2
    exit 2
}

source /cvmfs/cms.cern.ch/crab3/crab.sh

tmp="`cd /afs/cern.ch/user/s/shearsop/work/baobab-prod/CMSSW && scram runtime -sh`"

[ $? = 0 ] || die "Failed to set CMSSW runtime environment. Is directory /afs/cern.ch/user/s/shearsop/work/baobab-prod/CMSS existing?"

eval "$tmp"

#echo CMSSW_BASE: $CMSSW_BASE

[ $? = 0 ] || die "Failed to set CMSSW runtime environment."

function underline(){
    sed 'p
s/./-/g'
}

function run(){
    for d in $dirs; do
	{ echo $d | underline; echo; } | tee -a .warden_summary
	echo "Checking status of running tasks..."
	(cd "$d" && "$mydir/grow_baobabs" --check --no-crab-report-for-mc --report "$mailbox") 
	echo "Checking if some tasks need to be submitted..."
	(cd "$d" && "$mydir/grow_baobabs" --new-jobs)
	echo "Task summary:"
	(cd "$d" && "$mydir/grow_baobabs" --list) | tee -a .warden_summary
cat<<EOF | tee -a .warden_summary
======================================================================


EOF
    done	

}

#retrieves the name of the user running this script:
function user_name(){
    phonebook --uid `id -u` --terse firstname --terse surname | tr ';' ' '
}

function to_min(){
    exp=`echo "$1" | sed 's/w/10080/g
s/d/*1440+/g
s/h/*60+/g
s/m/+/g
s/[[:digit:]]*s//g
s/+$//g'`
    res="`echo "$exp" | bc -l`"
    if [ "$res" = 0 ]; then
	echo "Bad time expression" 2>&1
	echo 1440
    else
	echo "$res"
    fi
}


function help(){
    fmt -w ${COLUMNS:-80} <<EOF
Usage: warden [--loop CYCLE_TIME] [--report EVERY_CYCLE]

Shears framework [1]. Checks the status of Boabab production and takes the required actions: submission for new data or dataset, closing ending tasks, reporting new ntuple sets.

With the --loop option, the command runs every CYCLE_TIME. CYCLE_TIME default unit is minutes, w (week), d (day), h (hour) can be used and units can be combined, as 3d12h for 3 days 12 hours.

The --report allows email notification. The notifications are sent at EVERY_CYCLE iterations of the loop, use the value 1 for a promt notification.

Note: the command needs the grid authentication proxy to run and is not able to renew it on its own.

EOF
}

temp=`getopt -o hl:pr: --long help,loop:,report: \
     -n "$mybasename" -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

    # Note the quotes around `$TEMP': they are essential!
eval set -- "$temp"

unset loop
unset report_every
while true ; do
    case "$1" in
        -h|--help) help; exit 0;; 
        -l|--loop) loop="$2"; shift 2;;
	-r|--report) report_every="$2"; shift 2;;
        --) shift ; break ;; #end of options. It remains only the args.
        *) echo "Internal error!" ; exit 1 ;;
    esac
done



if [ "$1" = -h -a "$1" = --help ]; then
    help
    exit 0
fi

echo "$report_every" | grep -q '^[[:digit:]]*$' || { help; exit 1; }

trap "makeitnow=1" SIGHUP

[ -n "$loop" ] && cycle="`to_min $loop`"
i=0
do_run=y

while true; do
    
    [ -z "$loop" ] && do_run=n
    
    t=`date +%s`
    makeitnow=0
    
    cat > .warden_last_log <<EOF
File generated automatically by the warden command. The is ovewritten at each run cycle.

EOF
    cat > .warden_summary <<EOF
 ======================================================================
| Warden from the Shears framework                                     |
|                                                                      |
|       Summary of the current Boabab productions                      |
|                                                                      |
 ======================================================================

Productions monitored by warden:

EOF

for d in $dirs; do
    echo -n "$d " >> .warden_summary
    (cd $d && ./grow_baobabs --show-catalog | awk -F / '{f=NF-2; if(f>0) print $f}') >> .warden_summary
done

cat >> .warden_summary <<EOF

Last update: `date`

Operator: `user_name`

EOF
    
    run | tee -a .warden_last_log
    mv .warden_last_log warden_last_log
    mv .warden_summary warden_summary

    cp -a warden_last_log /afs/cern.ch/user/s/shearsop/www/boabab_current_prod_log.txt
    cp -a  warden_summary /afs/cern.ch/user/s/shearsop/www/boabab_current_prod_summary.txt
    i=$((i+1))

    if [ "$i" = "$report_every" ]; then
	echo "Checking for notifications to send."
	"$mydir/send_shears_emails"
	i=0
    fi
    
    [ -z "$loop" ] && break

    t1=`date +%s`
    dt=$((60*cycle+t-t1))
    echo "`date +'%F %R:%S'` sleeping $dt s... send me a SIGHUP to wake me up..."
    while [ $dt -gt 0 -a $makeitnow != 1 ]; do
        sleep 10
        t1=`date +%s`
        dt=$((60*cycle+t-t1))
    done
done
