#include "Pruner.h"
#include <iostream>
#include <vector>
using namespace std;

//Includes code generated by TTree:MakeClass():
//The fields of EventTree.h class will be used
//to access the EventTree contents. EventTree::Init(TTree*)
//should be called by the init(Tree*) method to link these
//fields to the EventTree contents.
#define EventTree_cxx
#include "EventTree.h"
void EventTree::Loop(){} //To make the compiler/linker happy.

/** Selection parameters **/

static float minGJetPt = 10;

static float minLepPt = 5;

static float minJetAk04Pt = 15;

/**************************/


class VJetPruner: public Pruner, EventTree{
protected:
  void declareSubSelections();
  bool init(TChain* tree);
  bool filterEvent();
  
  bool filterGLep(int iGenLep);
  bool filterGJet(int iGenLep);

  bool filterEl(int iEl);
  bool filterMu(int iMu);
  bool filterJetAk04(int iJetAk04);
  
  void makeFilterMask(bool (VJetPruner::*filter)(int), std::vector<bool>& mask);
  void skimCollections();
  bool eventSelection();

  enum { DMu, DMuUnf, DE, DEUnf, EMu, SE, SEUnf, SMu, SMuUnf, NSubSels
  } subsel_;

  static const int kEl = 11;
  static const int kMu = 13;
};

DECLARE_PRUNER(VJetPruner, "Pruner of W/Z + jet analyses")

void VJetPruner::declareSubSelections(){
  subSelections_.resize(NSubSels);
  subSelections_[DMu]    = SubSelection("DMu", "Dimuon selection for Z+jet analysis");
  subSelections_[DMuUnf] = SubSelection("DMuUnf", "Di-muon selection for Z+jet analysis with MC selection suitable to fill the detectot response matrices for the unfolding.");
  subSelections_[DE]     = SubSelection("DE","Dielectron selection for Z+jet analysis");
  subSelections_[DEUnf]  = SubSelection("DEUnf", "Dielectron selection for Z+jet analysis with MC selection suitable to fill the detectot response matrices for the unfolding.");
  subSelections_[EMu]    = SubSelection("EMu", "Electron-muon selection for background control region");
  subSelections_[SE]     = SubSelection("SE", "Single electron selection for W+jet analysis");
  subSelections_[SEUnf]  = SubSelection("SEUnf", "Single electron selection for W+jet analysis with MC selection suitable to fill the detectot response matrices for the unfolding.");
  subSelections_[SMu]    = SubSelection("SMu", "Single muon selection for W+jet analysis");
  subSelections_[SMuUnf] = SubSelection("SMuUnf", "Single muon selection for W+jet analysis with MC selection suitable to fill the detectot response matrices for the unfolding.");
}

bool VJetPruner::init(TChain* tree){
  if(tree == 0) return false;
  EventTree::Init(tree);
  return true;
}

void VJetPruner::makeFilterMask(bool (VJetPruner::*filter)(int), std::vector<bool>& mask){
  for(unsigned i = 0; i < mask.size(); ++i){
    mask[i] = (this->*filter)(i);
  }
}

bool VJetPruner::filterEvent(){
  skimCollections();
  return eventSelection() && Pruner::filterEvent();
}
  
void VJetPruner::skimCollections(){
  std::vector<bool> mask;
  
  //Gen lepton collections:
  mask.resize(GLepDr01Pt->size());
  makeFilterMask(&VJetPruner::filterGLep, mask);
  filter(GLepDr01Pt,  mask);
  filter(GLepDr01Eta, mask);
  filter(GLepDr01Phi, mask);
  filter(GLepDr01E,   mask);
  filter(GLepDr01Id,  mask);
  filter(GLepDr01St,  mask);
  filter(GLepDr01MomId, mask);

  //Gen jet collections:
  mask.resize(GJetAk04Pt->size());
  makeFilterMask(&VJetPruner::filterGJet, mask);
  filter(GJetAk04Pt,  mask);
  filter(GJetAk04Eta, mask);
  filter(GJetAk04Phi, mask);
  filter(GJetAk04E,   mask);
  filter(GJetAk04ChFrac, mask);

  //Reco muon collections:
  mask.resize(MuPt->size());
  makeFilterMask(&VJetPruner::filterMu, mask);
  filter(MuPt, mask);
  filter(MuEta, mask);
  filter(MuPhi, mask);
  filter(MuE, mask);
  filter(MuId, mask);
  filter(MuIdTight, mask);
  filter(MuCh, mask);
  filter(MuVtxZ, mask);
  filter(MuDxy, mask);
  filter(MuIsoRho, mask);
  filter(MuPfIso, mask);
  filter(MuType, mask);
  filter(MuIsoTkIsoAbs, mask);
  filter(MuIsoTkIsoRel, mask);
  filter(MuIsoCalAbs, mask);
  filter(MuIsoCombRel, mask);
  filter(MuTkNormChi2, mask);
  filter(MuTkHitCnt, mask);
  filter(MuMatchedStationCnt, mask);
  filter(MuDz, mask);
  filter(MuPixelHitCnt, mask);
  filter(MuTkLayerCnt, mask);
  filter(MuPfIsoChHad, mask);
  filter(MuPfIsoNeutralHad, mask);
  filter(MuPfIsoRawRel, mask);
  filter(MuHltMatch, mask);

  //Reco electron collections:
  mask.resize(ElPt->size());
  makeFilterMask(&VJetPruner::filterEl, mask);
  filter(ElPt, mask);
  filter(ElEta, mask);
  filter(ElEtaSc, mask);
  filter(ElPhi, mask);
  filter(ElE, mask);
  filter(ElId, mask);
  filter(ElCh, mask);
  filter(ElMvaTrig, mask);
  filter(ElMvaNonTrig, mask);
  filter(ElMvaPresel, mask);
  filter(ElDEtaTkScAtVtx, mask);
  filter(ElDPhiTkScAtVtx, mask);
  filter(ElHoE, mask);
  filter(ElSigmaIetaIeta, mask);
  filter(ElSigmaIetaIetaFull5x5, mask);
  filter(ElEinvMinusPinv, mask);
  filter(ElD0, mask);
  filter(ElDz, mask);
  filter(ElExpectedMissingInnerHitCnt, mask);
  filter(ElPassConvVeto, mask);
  filter(ElHltMatch, mask);
  filter(ElPfIsoChHad, mask);
  filter(ElPfIsoNeutralHad, mask);
  filter(ElPfIsoIso, mask);
  filter(ElPfIsoPuChHad, mask);
  filter(ElPfIsoRaw, mask);
  filter(ElPfIsoDbeta, mask);
  filter(ElPfIsoRho, mask);
  filter(ElAEff, mask);
  
  //Reco jet collections:
  mask.resize(JetAk04Pt->size());
  makeFilterMask(&VJetPruner::filterJetAk04, mask);
}


//to be run after skimCollections
bool VJetPruner::eventSelection(){
  //count gen leptons:
  int GElCnt = 0;
  int GMuCnt = 0;
  for(unsigned i = 0; i < GLepDr01Id->size(); ++i){
    if(fabs((*GLepDr01Id)[i]) == kEl) ++GElCnt;
       if(fabs((*GLepDr01Id)[i]) == kMu) ++GMuCnt;
  }  

  
  switch(subsel_){
  case DMu:
    return MuPt->size() > 1;
    break;
  case DMuUnf:
    return MuPt->size() > 1  || GMuCnt > 1;
    break;
  case DE:
    return ElPt->size() > 1;
    break;
  case DEUnf:
    return ElPt->size() > 1 || GElCnt > 1;
    break;
  case EMu:
    return ElPt->size() > 0 && MuPt->size() > 0;
    break;
  case SE:
    return ElPt->size() > 0;
    break;
  case SEUnf:
    return ElPt->size() > 0 || GElCnt > 0;
    break;
  case SMu:
    return MuPt->size() > 0;
    break;
  case SMuUnf:
    return MuPt->size() > 0 || GMuCnt > 0;
    break;
  case NSubSels:
  default:
    return false;
  }
};


bool VJetPruner::filterGLep(int iGenLep){
  return true;
}

bool VJetPruner::filterGJet(int iGenLep){
  return (*GJetAk04Pt)[iGenLep] > minGJetPt;
}

bool VJetPruner::filterMu(int iMu){
  return (*MuPt)[iMu] > minLepPt;
}

bool VJetPruner::filterEl(int iEl){
  return (*ElPt)[iEl] > minLepPt;
}

bool VJetPruner::filterJetAk04(int iJetAk04){
  return (*JetAk04Pt)[iJetAk04] > minJetAk04Pt;
}

