# This is the configuration file for the Higgs analysis, year 2016.
# Please keep it organized, and don't delete comments.

# Options related to output and logs
log:
    # Whether to use colors in the terminal.
    #Possible values: yes|no|auto (default: auto)
    color: auto

    # Controls what's printed to the screen.
    # Possible values: debug|info|warn|error|fatal (default: info)
    log level: info

    # Pipe logs to the given log file, comment out for no log.
    log file: log16.txt

    # Controls what's written in the log file.
    # Possible values: debug|info|warn|error|fatal (default: debug)
    log file level: debug

    # Whether to override ROOT's default log handler.
    # Default value: yes
    #override root handler: yes


# when you want to separate a specific flavor from DY->ll events (e.g. Madgraph)
# it will check the dilepton flavor at the generator level, and skip the events if the flavor is not same with the given flavor
# WARNING: It should be used for *DY MC only*. Background MC with this option will give meaningless results.
# default: false
Select specific flavor in DYLL:
  use: false
  flavor: -1 # pdgID. DY->ee: 11 / DY->mm: 13 / DY->tautau: 15

# Cut on the inclusive DYJets sample
use exclusive mass binned DYJets samples: yes

# dilepton pt reweighting option
# the reweighting factor is derived from (data-bkg) vs. DY MC comparison of dilepton pT @ reco-level
# WARNING: it should be applied to *DY MC only* (i.e not use for backgrounds)
# default: false
dilepton pt reweighting:
  use: false
  reweighting factor path: "." # -- under EfficiencyTables/ (e.g. 2016preAPV/ROOTFile_DimuonPt_Weight_Madgraph.root)

# Whether to use pileup reweighing
# Default value: true
use pileup reweighing: true

# specify the type for the pileup
# options:
# - 2016_PreAPV, 2016_PostAPV
# - 2016_PreAPV_emu, 2016_PostAPV_emu (for the data collected with the emu trigger)
# - 2017
# - 2018
pileup type: 2016_PreAPV

# Whether results are preliminary (for plots)
preliminary: yes

# definition of the phase space to be unfolded
generator level:
  # minimum pt on gen leptons [GeV]
  # default: 20 GeV
  lepton pt: 15

  # minimum pt on gen leptons [GeV]
  # default: 25 GeV
  leading lepton pt: 20

  # maximum lepton |eta| cut
  # default: 2.4
  lepton eta: 2.4

# Options related to the selection of jets
jets:
    # Pt cut [GeV]
    # Default value: 30
    pt: 30

    # Rapidity cut
    # Default value: 2.4
    rapidity: 2.4

    # PU MVA cut
    # Default value: -0.2
    pu mva: -0.2

    # deltaR(jet, lepton) cut
    # Default value: 0.4
    lepton delta r: 0.4

    # Whether to apply jet energy smearing
    # Default value: yes
    JER smearing: yes

prefiring weights:
    # Whether to apply prefiring weights
    use: yes
    # syst. variation mode
    # 0 = nominal / 1 = up variation / -1 = down variation
    mode: 0

# Options of the b jet veto
b jet veto:
    # Whether to cut events with b jets
    # Default value: yes
    use: no

    # Working point; see the b tagging POG TWiki for recommended working points
    # Allowed values: loose, medium, tight
    # Default value: loose
    working point: medium

    # Location of the scale factors csv file. Interpreted relative to the
    # EfficiencyTables/ directory.
    # Default value: CSVv2_Moriond17_B_H.csv
    scale factor path: CSVv2_Moriond17_B_H.csv

# Options related to the selection of electrons
electrons:
    # Pt cut [GeV]
    # Default value: 20
    pt: 20

    # Eta cut
    # Default value: 2.4
    eta: 2.4

    # Relative isolation cut
    # Default value: 0.25
    isolation: 999999999.

    # Id
    # Possible values: loose, medium, tight
    # Default value: tight
    id: medium

    # Whether to use the identification scale factors
    # Default value: yes
    use id scale factors: no

    # Whether to use the reconstruction scale factors
    # Default value: yes
    use reconstruction scale factors: no

# Options related to the selection of muons
muons:
    # Pt cut [GeV]
    # Default value: 20
    pt: 15

    # Eta cut
    # Default value: 2.4
    eta: 2.4

    # Relative isolation cut
    # Default value: 0.25
    #isolation: 0.15

    #Iso
    # Possible values: veryloose, loose, medium, tight
    iso: tight

    # Id
    # Possible values: loose, medium, tight
    # Default value: tight
    id: tight

    # Whether to use the identification scale factors
    # Default value: yes
    use id scale factors: yes

    # Whether to use the isolation scale factors
    # Default value: yes
    use isolation scale factors: yes

    # Whether to use the tracking scale factors
    # Default value: yes
    use tracking scale factors: no

    # Whether to use Rochester correction
    # Default value: yes
    use rochester correction: yes

    # Path to the directory containing tables for Rochester corrections. Interpreted relative to
    # the EfficiencyTables/ directory.
    # Default value: rcdata.2016.v3
    rochester correction path: 2016preAPV/RoccoR2016aUL.txt
    #rochester correction path: rcdata.2016.v3

# Good Z boson settings
Z:
    # leading "lepton" pT cut [GeV]
    # Default value: 25
    leading lepton pt: 20

    # m(ll)/pt(lep, sub) < X cut: reduce QCD in high mass region
    mll/subleading lepton pt: 10

    # Low mass bound [GeV]
    # Default value: 0
    low mass: 40

    # High mass bound [GeV]
    # Default value: infinity
    high mass: 3000

    # Charge check mode
    # Possible values:
    #   - none: No check
    #   - neutral: Keep only lepton pairs of opposite sign
    #   - same sign: Keep only lepton pairs of the same sign
    # Default value: neutral
    charge mode: neutral

    # Flavor check mode
    # Possible values:
    #   - none: No check
    #   - same: Two leptons of the same flavor
    #   - ee: Two electrons
    #   - mumu: Two muons
    #   - emu: One electron and one muon
    # Default value: same
    flavor mode: mumu

# How the measurement is binned in mass
# Default value: empty
mass bins: [ 40, 50, 76, 106, 170, 350, 1000, 3000 ]

# Triggers
#
# The values below must be strings; use an empty string to disable triggers. See the documentation
# of physics::trigger_mask for more details.
triggers: |
    HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL,
    HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL,
    HLT_IsoMu24,
    HLT_IsoTkMu24

use trigger scale factors: yes

# select the best trigger SF depending on leading muon pt & fired trigger
# this feature is only needed for the dimuon analysis
select the best muon trigger SF:
  # default: true
  # if it is false, shears will always select single muon trigger SF (can be used for test jobs)
  use: true

  # single muon triggers used
  single muon triggers: |
    HLT_IsoMu24,
    HLT_IsoTkMu24

  # double muon triggers
  double muon triggers: |
    HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL,
    HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL

  # pt criteria for which trigger is used
  # leading pt < pt criteria: use DMu / leading pt > pt criteria: use SMu
  pt criteria: 26

  # reject the events that fires single muon triggers "only" (i.e not pass dimuon triggers)
  # but with pT(leading) < (pt_criteria) GeV muons (muons in turn-on curve or below)
  # these events are not used due to the large SF
  # reject or not (default: false)
  reject low quality muon events: true

# Reweighting for top backgrounds (emu method)
emu method reweighting:
  use: yes
  offset: 1.14853
  slope: -0.106471

# List of available data/MC samples
samples:
    ### DATA
    - name: data
      type: data
      jobs: 45
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_DoubleMuon_data.txt
      triggers: |
          HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL,
          HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL
    # Note: This sample has to be hadd-ed with 'data'.
    #- name: data
    - name: data-smu
      type: data
      jobs: 16
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_SingleMuon_data.txt
      triggers: |
          ^HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL,
          ^HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL,
          HLT_IsoMu24,
          HLT_IsoTkMu24
    # ### MC
    # #- name: DYJets
    # #  type: MC
    # #  jobs: 20
    # #  nano dir: Catalogs/2016preAPV
    # #  catalog: Catalog2016_bonzai_DYJetsToMuMu.txt
    # - name: DYJets_M-10to50
    #   type: MC
    #   jobs: 7
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-10to50.txt
    # #- name: DYJets_M-10to40
    # #  type: MC
    # #  jobs: 2
    # #  nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    # #  catalog: Catalog2016_bonzai_DYJetsToMuMu_M-10to40.txt
    # #- name: DYJets_M-40to50
    # #  type: MC
    # #  jobs: 2
    # #  nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    # #  catalog: Catalog2016_bonzai_DYJetsToMuMu_M-40to50.txt
    # - name: DYJets_M-50to100
    #   type: MC
    #   jobs: 22
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-50to100.txt
    # - name: DYJets_M-100to200
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-100to200.txt
    # - name: DYJets_M-200to400
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-200to400.txt
    # - name: DYJets_M-400to500
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-400to500.txt
    # - name: DYJets_M-500to700
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-500to700.txt
    # - name: DYJets_M-700to800
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-700to800.txt
    # - name: DYJets_M-800to1000
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-800to1000.txt
    # - name: DYJets_M-1000to1500
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-1000to1500.txt
    # - name: DYJets_M-1500to2000
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-1500to2000.txt
    # - name: DYJets_M-2000toInf
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-2000toInf.txt
    ### BACKGROUND
    - name: ST_s-channel
      type: background
      nano dir: Catalogs/2016preAPV/
      catalog: Catalog2016_bonzai_ST_s-channel.txt
    - name: ST_t-channel_antitop
      type: background
      nano dir: Catalogs/2016preAPV/
      catalog: Catalog2016_bonzai_ST_t-channel_antitop.txt
    - name: ST_t-channel_top
      type: background
      jobs: 3
      nano dir: Catalogs/2016preAPV/
      catalog: Catalog2016_bonzai_ST_t-channel_top.txt
    - name: ST_tW_antitop
      type: background
      nano dir: Catalogs/2016preAPV/
      catalog: Catalog2016_bonzai_ST_tW_antitop.txt
    - name: ST_tW_top
      type: background
      nano dir: Catalogs/2016preAPV/
      catalog: Catalog2016_bonzai_ST_tW_top.txt
    #- name: WJetsToLNu
    #  type: background
    #  jobs: 4
    #  nano dir: Catalogs/2016preAPV/
    #  catalog: Catalog2016_bonzai_WJetsToLNu.txt
    # - name: WWTo2L2Nu
    #   type: background
    #   nano dir: Catalogs/2016preAPV
    #   catalog: Catalog2016_bonzai_WWTo2L2Nu.txt
    # - name: WZ
    #   type: background
    #   nano dir: Catalogs/2016preAPV
    #   catalog: Catalog2016_bonzai_WZ.txt
    # - name: ZZ
    #   type: background
    #   jobs: 5
    #   nano dir: Catalogs/2016preAPV
    #   catalog: Catalog2016_bonzai_ZZ.txt
    - name: TT
      type: background
      jobs: 10
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_TTTo2L2Nu.txt
    # - name: TauTau
    #   type: background
    #   jobs: 3
    #   nano dir: Catalogs/2016preAPV
    #   catalog: Catalog2016_bonzai_TauTau.txt
    # - name: GammaGamma
    #   type: background
    #   nano dir: Catalogs/2016preAPV
    #   catalog: Catalog2016_bonzai_GGToLL.txt
    # - name: GammaGamma_M-5to50
    #   type: background
    #   nano dir: Catalogs/2016preAPV
    #   catalog: Catalog2016_bonzai_GGToLL_M-5to50.txt
    # # Uncomment below only for reco histogram drawing when you have the fakes from SS method!
    # - name: Fakes
    #   type: background
    #   nano dir: Catalogs/2016preAPV
    #   catalog: Catalog2016_bonzai_SingleMuon_data.txt

# Scale factors
tables:
    muon id:        2016preAPV/Efficiencies_muon_generalTracks_Z_Run2016_UL_HIPM_ID_TightID.txt
    muon isolation: 2016preAPV/Efficiencies_muon_generalTracks_Z_Run2016_UL_HIPM_ISO_NUM_TightRelIso_DEN_TightIDandIPCut.txt
    #muon tracking: 2016preAPV/Efficiencies_muon_generalTracks_Run2016preVFP_UL_trackerMuon.txt
    dimu trigger:   2016preAPV/ScaleFactor_DoubleMuonTriggers_UL2016_HIPM_Tight.txt
    smu trigger data: 2016preAPV/Efficiencies_muon_generalTracks_Z_Run2016_UL_HIPM_SingleMuonTriggers_Data.txt
    smu trigger mc: 2016preAPV/Efficiencies_muon_generalTracks_Z_Run2016_UL_HIPM_SingleMuonTriggers_MC.txt

# Reweighing (eg for merged samples)
#
# For each possible reweighing, the syntax is:
#
#   sample name: table.txt
#
# The table should contain the numbers needed for reweighing. In order to be
# useful, several samples will often share the same table.
#
# The tables can be derived by tweaking Main/dyjets-sample-weights.cc.
#reweighing:
#    # Based on the number of partons npNLO
#    npNLO:
#        DYJets:     merging-DYJets-npNLO.txt
#        DYJets-0J:  merging-DYJets-npNLO.txt
#        DYJets-1J:  merging-DYJets-npNLO.txt
#        DYJets-2J:  merging-DYJets-npNLO.txt

# How to group MC samples when drawing Data/MC comparisons
MC grouping:
    # - legend: "Z/#gamma^{*} #rightarrow #mu#mu"
    #   required: yes
    #   #samples: [ DYJets ]
    #   samples: [ DYJets_M-10to50, DYJets_M-50to100, DYJets_M-100to200, DYJets_M-200to400, 
    #              DYJets_M-400to500, DYJets_M-500to700, DYJets_M-700to800, DYJets_M-800to1000, 
    #              DYJets_M-1000to1500, DYJets_M-1500to2000, DYJets_M-2000toInf ]
    #   color: 408 # kGreen - 8
    #   is signal: yes
    - legend: "t#bar{t}"
      samples: [ TT ]
      color: 600 # kBlue
    # - legend: VV
    #   samples: [ ZZ, WWTo2L2Nu, WZ ]
    #   color: 633 # kRed + 1
    - legend: Single top
      samples: [ ST_s-channel, ST_t-channel_antitop, ST_t-channel_top, ST_tW_antitop, ST_tW_top ]
      color: 616 # kMagenta
    # - legend: DY TauTau
    #   samples: [ TauTau ]
    #   color: 434 # kCyan + 2
    # - legend: "#gamma#gamma"
    #   samples: [ GammaGamma, GammaGamma_M-5to50 ]
    #   color: 800 # kOrange
    # # Uncomment below only for reco histogram drawing when you have the fakes from SS method!
    # - legend: "Fakes"
    #   samples: [ Fakes ]
    #   color: 803 # kOrange + 3

# The file below defines the binnings for histograms relevant to the analysis.
# Default value: dyjets-binnings.yml
binning file: dyjets-binnings.yml

# Plot properties
#
# The sole mandatory field is the "selector", containing a regex that is matched
# against plot names. When a plot name matches the regex, properties listed in
# other fields are assigned to it. In general, rules lower in the list take
# precedence over the ones above them, but for some properties they add up.
#
# Supported properties:
#   - produce (yes): Whether to make the plot
#   - log x (no): Whether to x axis should use a log scale
#   - ratio min (0.601): The minimum value shown on data/mc ratio plots
#   - ratio max (1.399): The maximum value shown on data/mc ratio plots
#   - x axis label: The label of the x axis. Captures from the selector can be
#                   used to provide dynamic labels.
#   - x axis detail: Text that will appear in parenthesis after the axis label.
#                    Several labels can be added this way. Captures from the
#                    selector can be used to provide dynamic labels.
#   - x axis unit: The unit of the x axis. Appears between square brackets after
#                  the main label. Captures from the selector can be used to
#                  provide dynamic labels.
plots:
    # Excluded plots
    - selector: '.*'
      produce: no
    - selector: 'mu.*inc0jet'
      produce: yes
    - selector: '.*leading.*'
      produce: no
    - selector: '.*exc.*'
      produce: no
    - selector: 'mass_wide_range_inc0jet'
      produce: yes
    - selector: 'pt_inc0jet'
      produce: yes
    - selector: 'rapidity_inc0jet'
      produce: yes
    - selector: 'phistar_inc0jet'
      produce: yes
    - selector: 'MET_pt_inc0jet'
      produce: yes
    - selector: 'MET_vs_mass_inc0jet'
      produce: yes
    - selector: 'mll_over_ptsub_inc0jet'
      produce: yes
    # Style changes
    - selector: '.*'
      ratio min: 0.901
      ratio max: 1.099
    - selector: '^phistar.*'
      log x: yes
    - selector: '^pt.*'
      log x: yes
    - selector: '^mass_wide.*'
      log x: yes
    - selector: 'dyjets_events.*inc0jet'
      ratio min: 0.901
      ratio max: 1.099
    # Axis labels
    - selector: '^mass.*'
      x axis label: 'M_{#mu#mu}'
      x axis unit: 'GeV'
    - selector: '^nJets.*'
      x axis label: 'Exclusive number of jets'
    - selector: '^nJetsIncl.*'
      x axis label: 'Inclusive number of jets'
    - selector: '^phistar.*'
      x axis label: '#phi*'
    - selector: '^pt.*'
      x axis label: 'p_{T}^{#mu#mu}'
      x axis unit: 'GeV'
    - selector: '.+mass(.*)_(.*).*'
      x axis detail: '$1 #leq M_{#mu#mu} < $2 GeV'
    - selector: '.*inc(1|2)jet.*'
      x axis detail: 'N_{jets} #geq $1'
    - selector: '.*exc(1|2)jet.*'
      x axis detail: 'N_{jets} = $1'
