#include "Pruner.h"
#include <iostream>
#include <vector>
#include "TLorentzVector.h"
#include <cstdlib>
using namespace std;

//Includes code generated by TTree:MakeClass():
//The fields of EventTree.h class will be used
//to access the EventTree contents. EventTree::Init(TTree*)
//should be called by the init(Tree*) method to link these
//fields to the EventTree contents.
//#define EventTree_cxx
#include "EventTree.h"

//void EventTree::Loop(){} //To make the compiler/linker happy.

/** Selection parameters **/
enum {SingleMu,SingleE, Ntrig}; //List of triggers used for our analysis
//The lines below correspond to the triggerBits used in our analysis. These are all defined in the trigger2016.h file of the ntuple producer.
static int trigSingleMu[2] = {11,16};
static int trigSingleE[1] = {9};



static float minLepPt = 10;

static float mll_low = 60;
static float mll_high = 120;

static const unsigned elIdMask = (1 <<10); //that is 1024;

//For data v11
//static const unsigned elIdMask = (1 <<20);

class TagProbePruner: public Pruner, EventTree{

protected:
	void declareSubSelections();
  	bool init(TChain* tree);
  	bool filterEvent();

 

  	bool filterEl(int iEl);
  	bool filterMu(int iMu);

  	bool isTightEle(std::vector<float> *ElPt, std::vector<float> *ElEta, std::vector<float> *ElPhi, std::vector<float> *ElE, std::vector<unsigned int> *ElId, std::vector<float> *ElEtaSc, std::vector<float> *ElPfIsoRho);
  	bool isTightMuon(std::vector<float> *MuPt, std::vector<float> *MuEta, std::vector<float> *MuPhi, std::vector<float> *MuE, std::vector<unsigned int> *MuId, std::vector<unsigned int> *MuIdTight, std::vector<float> *MuPfIso);

  	
  	void makeFilterMask(bool (TagProbePruner::*filter)(int), std::vector<bool>& mask);
  	void skimCollections();
  	bool eventSelection();

  	bool passTrigger(int trig);
  	double mll(std::vector<float>* lepColPt, std::vector<float>* lepColEta,
	     std::vector<float>* lepColPhi, std::vector<float>* lepColE,
	     std::vector<int>* lepColId = 0, int pid = 0);
  	enum { Mu, Ele,NSubSels};

  static const int kEl = 11;
  static const int kMu = 13;
};

DECLARE_PRUNER(TagProbePruner, "Pruner of Tag & Probe analysis")

void TagProbePruner::declareSubSelections(){
	subSelections_.resize(NSubSels);
	subSelections_[Mu]		= SubSelection("Mu","muon selection for Tag & Probe");
	subSelections_[Ele]		= SubSelection("Ele","electron selection for Tag & Probe");
//	subSelections_[SMu]		= SubSelections("SMu","single muon selection for Tag & Probe");
//	subSelections_[SE]		= SubSelections("SE","single electron selection for Tag & Probe");
	
}

bool TagProbePruner::init(TChain* tree){
  if(tree == 0) return false;
  EventTree::Init(tree);
  return true;
}

void TagProbePruner::makeFilterMask(bool (TagProbePruner::*filter)(int), std::vector<bool>& mask){
  for(unsigned i = 0; i < mask.size(); ++i){
    mask[i] = (this->*filter)(i);
  }
}

bool TagProbePruner::filterEvent(){
  skimCollections();
  return eventSelection() && Pruner::filterEvent();
}

void TagProbePruner::skimCollections(){
  std::vector<bool> mask;

  //Reco muon collections:
  mask.resize(MuPt->size());
  makeFilterMask(&TagProbePruner::filterMu, mask);
  filter(MuPt, mask);
  filter(MuEta, mask);
  filter(MuPhi, mask);
  filter(MuE, mask);
  filter(MuId, mask);
  filter(MuIdTight, mask);
  filter(MuCh, mask);
  filter(MuVtxZ, mask);
  filter(MuDxy, mask);
  filter(MuIsoRho, mask);
  filter(MuPfIso, mask);
  filter(MuType, mask);
  filter(MuIsoTkIsoAbs, mask);
  filter(MuIsoTkIsoRel, mask);
  filter(MuIsoCalAbs, mask);
  filter(MuIsoCombRel, mask);
  filter(MuTkNormChi2, mask);
  filter(MuTkHitCnt, mask);
  filter(MuMatchedStationCnt, mask);
  filter(MuDz, mask);
  filter(MuPixelHitCnt, mask);
  filter(MuTkLayerCnt, mask);
  filter(MuPfIsoChHad, mask);
  filter(MuPfIsoNeutralHad, mask);
  filter(MuPfIsoRawRel, mask);
  filter(MuHltMatch, mask);

  //Reco electron collections:
  mask.resize(ElPt->size());
  makeFilterMask(&TagProbePruner::filterEl, mask);
  filter(ElPt, mask);
  filter(ElEta, mask);
  filter(ElEtaSc, mask);
  filter(ElPhi, mask);
  filter(ElE, mask);
  filter(ElId, mask);
  filter(ElCh, mask);
  filter(ElMvaTrig, mask);
  filter(ElMvaNonTrig, mask);
  filter(ElMvaPresel, mask);
  filter(ElDEtaTkScAtVtx, mask);
  filter(ElDPhiTkScAtVtx, mask);
  filter(ElHoE, mask);
  filter(ElSigmaIetaIeta, mask);
  filter(ElSigmaIetaIetaFull5x5, mask);
  filter(ElEinvMinusPinv, mask);
  filter(ElD0, mask);
  filter(ElDz, mask);
  filter(ElExpectedMissingInnerHitCnt, mask);
  filter(ElPassConvVeto, mask);
  filter(ElHltMatch, mask);
  filter(ElPfIsoChHad, mask);
  filter(ElPfIsoNeutralHad, mask);
  filter(ElPfIsoIso, mask);
  filter(ElPfIsoPuChHad, mask);
  filter(ElPfIsoRaw, mask);
  filter(ElPfIsoDbeta, mask);
  filter(ElPfIsoRho, mask);
  filter(ElAEff, mask);
}

double TagProbePruner::mll(std::vector<float>* lepColPt, std::vector<float>* lepColEta,
		       std::vector<float>* lepColPhi, std::vector<float>* lepColE, 
		       std::vector<int>* lepColId, int pid){
  int i0 = -1; double pt0 = 0;
  int i1 = -1; double pt1 = 0;
  //look for the two highest pt leptons:
  for(size_t i = 0; i < lepColPt->size(); ++i){
    if(lepColId && abs((*lepColId)[i]) != pid) continue;
    if((*lepColPt)[i] > pt0) {
      i1 = i0;
      pt1 = pt0;
      i0 = i;
      pt0 = (*lepColPt)[i];
    } else if((*lepColPt)[i] > pt1) {i1 = i; pt1 = (*lepColPt)[i]; }
  }
 // std::cerr << __FILE__ << ":" << __LINE__ << ": " << i0 << i1 << "\n";
  if(i1 <0) return -1;
  else{
    TLorentzVector v0;
    v0.SetPtEtaPhiE((*lepColPt)[i0],(*lepColEta)[i0],(*lepColPhi)[i0],(*lepColE)[i0]);
    TLorentzVector v1;
    v1.SetPtEtaPhiE((*lepColPt)[i1],(*lepColEta)[i1],(*lepColPhi)[i1],(*lepColE)[i1]);
    return (v0 + v1).M();
  }
}
bool TagProbePruner::isTightEle(std::vector<float> *ElPt, std::vector<float> *ElEta, std::vector<float> *ElPhi, std::vector<float> *ElE, std::vector<unsigned int> *ElId, std::vector<float> *ElEtaSc, std::vector<float> *ElPfIsoRho)
{
	bool Eallpass= false;
for(unsigned int i = 0 ; i<ElPt->size() ; i++){
      bool passEta = false, passIso = false, passId = false, passPt = false;
      TLorentzVector currentLepton; currentLepton.SetPtEtaPhiE(ElPt->at(i),ElEta->at(i),ElPhi->at(i),ElE->at(i));
       //Id //Very temporary!!! Used without much cross-checking.
      passId = ElId->at(i) & (1<<17);
      //passLooseId = ElId->at(i) & (1<<16);
      int eta = fabs(ElEtaSc->at(i));//I took the supercluster eta since it's really the geometry which is taken here.
      passEta = (eta<=2.5 && (eta>=1.5660 || eta<=1.4442));
      //Iso //We use ElPfIsoRho for now, we'll see after if it's mandatory to refine it. Iso is applied only for the "tight" selection, not for the extra lepton veto.
      if(eta>=1.5660 && ElPfIsoRho->at(i)<0.0646) passIso = true;
      if(eta<=1.4442 && ElPfIsoRho->at(i)<0.0354) passIso = true; //Numbers are taken from llvv_fwk and have not been checked.
      passPt = (currentLepton.Pt() >=30);
      //passLoosePt = (currentLepton.Pt() >=10);
      
 		Eallpass =Eallpass||(passEta && passIso && passId && passPt);
    }
    return Eallpass;
}
bool TagProbePruner::isTightMuon(std::vector<float> *MuPt, std::vector<float> *MuEta, std::vector<float> *MuPhi, std::vector<float> *MuE, std::vector<unsigned int> *MuId, std::vector<unsigned int> *MuIdTight, std::vector<float> *MuPfIso)
{
	bool Mallpass = false;
	for(unsigned int i = 0 ; i<MuPt->size() ; i++){
      bool passEta = false, passIso = false, passId = false, passPt = false;
      TLorentzVector currentLepton; currentLepton.SetPtEtaPhiE(MuPt->at(i),MuEta->at(i),MuPhi->at(i),MuE->at(i));
      //Id //Very temporary!!! Used without much cross-checking.
      passId = MuIdTight->at(i) & (1<<0); //Look at the first vertex, hence the bit 0.
      //passLooseId = MuId->at(i) & (1<<0);
      //passSoftId = false; //Don't know yet how to implement this thing. FIXME
      int eta = fabs(MuEta->at(i));
      passEta = (eta<=2.4);
      //Iso //We use MuPfIso for now, we'll see after if it's mandatory to refine it. Iso is applied only for the "tight" selection, not for the extra lepton veto.
      passIso = (MuPfIso->at(i)<0.15); //Numbers are taken from llvv_fwk and have not been checked.
      passPt = (currentLepton.Pt() >=25);
      //passLoosePt = (currentLepton.Pt() >=10);
      //passSoftPt = (currentLepton.Pt() >=3);
      Mallpass= Mallpass||(passEta && passIso && passId && passPt);
}
	return Mallpass;
}

bool TagProbePruner::passTrigger(int trig){
  vector<vector<int> > trigList(Ntrig);
  trigList[SingleMu].insert(trigList[SingleMu].end(),trigSingleMu,trigSingleMu+(sizeof(trigSingleMu)/sizeof(trigSingleMu[0])));
  trigList[SingleE].insert(trigList[SingleE].end(),trigSingleE,trigSingleE+(sizeof(trigSingleE)/sizeof(trigSingleE[0])));
  
  switch(trig){
 
  case SingleMu:
    for(unsigned int i = 0 ; i < trigList[SingleMu].size() ; i++)  if(TrigHltMu & (1<<trigList.at(SingleMu).at(i))) return true;
    break;
  case SingleE:
    for(unsigned int i = 0 ; i < trigList[SingleMu].size() ; i++)  if(TrigHltMu & (1<<trigList.at(SingleMu).at(i))) return false;
    for(unsigned int i = 0 ; i < trigList[SingleE].size() ; i++)  if(TrigHltEl & (1<<trigList.at(SingleE).at(i))) return true;
    break;
  case Ntrig://In this case (used for MC), take if any trigger passed
    for(unsigned int i = 0 ; i < trigList[SingleE].size() ; i++)  if(TrigHltEl & (1<<trigList.at(SingleE).at(i))) return true;
    for(unsigned int i = 0 ; i < trigList[SingleMu].size() ; i++)  if(TrigHltMu & (1<<trigList.at(SingleMu).at(i))) return true;
    break;
  default:
    return false;
  }
return false; //If nothing found.
}


bool TagProbePruner::eventSelection(){

	float m;
	bool passtightEle;
	bool passtightMu;
	switch(iSubSelection_){
  	case Mu:
   		m = mll(MuPt,MuEta,MuPhi,MuE);
   		passtightMu = isTightMuon(MuPt,MuEta,MuPhi,MuE,MuId,MuIdTight,MuPfIso);
    	return MuPt->size() > 1 && mll_low < m && m < mll_high  && passtightMu && passTrigger(SingleMu);

 	case Ele:
   		m = mll(ElPt,ElEta,ElPhi,ElE);
   		passtightEle = isTightEle(ElPt,ElEta,ElPhi,ElE,ElId,ElEtaSc,ElPfIsoRho);
    	return ElPt->size() > 1 && mll_low < m && m < mll_high && passtightEle && passTrigger(SingleE);

    
 	default:
    	return false;
  }
};

bool TagProbePruner::filterEl(int iEl) {
	

  return ElPt->size() >0&&(*ElPt)[iEl] > minLepPt;
	}

bool TagProbePruner::filterMu(int iMu){
	

  return MuPt->size() > 0 && ((*MuPt)[iMu] > minLepPt) ;
}







