#include "Pruner.h"
#include <iostream>
#include <vector>
#include "TLorentzVector.h"
#include <cstdlib>
using namespace std;

//Includes code generated by TTree:MakeClass():
//The fields of EventTree.h class will be used
//to access the EventTree contents. EventTree::Init(TTree*)
//should be called by the init(Tree*) method to link these
//fields to the EventTree contents.
/////#define EventTree_cxx
#include "EventTree.h"
/////void EventTree::Loop(){} //To make the compiler/linker happy.

/** Selection parameters **/

static float minLepPt = 25;


enum {DoubleMu, SingleMu, DoubleE, HighPtE, SingleE, EMu, SinglePhoton, Ntrig}; //List of triggers used for our analysis
//The lines below correspond to the triggerBits used in our analysis. These can be found under BitFields/TrigHltBlabla/data().
static int trigDoubleMu[4] = {18,19,20,21};
static int trigSingleMu[3] = {17,21,45}; //is missing IsoTkMu22
static int trigDoubleE[2] = {1,2};
static int trigSingleE[2] = {11,12}; //tight path is with eta2p1
static int trigEMu[2] = {0,2}; //all DZ paths missing, as well as Mu12Ele23
static int trigSinglePhoton[10] = {32,30,24,20,55,49,44,38,33,28};


/**************************/


class ZZ2l2vPruner: public Pruner, EventTree{
protected:
  void declareSubSelections();
  bool init(TChain* tree);
  bool filterEvent();
  
  bool filterEl(int iEl);
  bool filterMu(int iMu);
  
  void makeFilterMask(bool (ZZ2l2vPruner::*filter)(int), std::vector<bool>& mask);
  void skimCollections();
  bool eventSelection();
  bool passAnyTrigger();
  enum { DMu, DE, NSubSels};
};

DECLARE_PRUNER(ZZ2l2vPruner, "Pruner of ZZ2l2v analysis")

void ZZ2l2vPruner::declareSubSelections(){
  subSelections_.resize(NSubSels);
  subSelections_[DMu]    = SubSelection("DMu", "Dimuon selection for ZZ2l2v analysis");
  subSelections_[DE]     = SubSelection("DE","Dielectron selection for ZZ2l2v analysis");
}

bool ZZ2l2vPruner::init(TChain* tree){
  if(tree == 0) return false;
  EventTree::Init(tree);
  return true;
}

void ZZ2l2vPruner::makeFilterMask(bool (ZZ2l2vPruner::*filter)(int), std::vector<bool>& mask){
  for(unsigned i = 0; i < mask.size(); ++i){
    mask[i] = (this->*filter)(i);
  }
}

bool ZZ2l2vPruner::filterEvent(){
  skimCollections();
  return eventSelection() && Pruner::filterEvent();
}
  
void ZZ2l2vPruner::skimCollections(){
  std::vector<bool> mask;
  
  //Reco muon collections:
  mask.resize(MuPt->size());
  makeFilterMask(&ZZ2l2vPruner::filterMu, mask);
  filter(MuPt, mask);
  filter(MuEta, mask);
  filter(MuPhi, mask);
  filter(MuE, mask);
  filter(MuId, mask);
  filter(MuIdTight, mask);
  filter(MuCh, mask);
  filter(MuVtxZ, mask);
  filter(MuDxy, mask);
  filter(MuIsoRho, mask);
  filter(MuPfIso, mask);
  filter(MuType, mask);
  filter(MuIsoTkIsoAbs, mask);
  filter(MuIsoTkIsoRel, mask);
  filter(MuIsoCalAbs, mask);
  filter(MuIsoCombRel, mask);
  filter(MuTkNormChi2, mask);
  filter(MuTkHitCnt, mask);
  filter(MuMatchedStationCnt, mask);
  filter(MuDz, mask);
  filter(MuPixelHitCnt, mask);
  filter(MuTkLayerCnt, mask);
  filter(MuPfIsoChHad, mask);
  filter(MuPfIsoNeutralHad, mask);
  filter(MuPfIsoRawRel, mask);
  filter(MuHltMatch, mask);

  //Reco electron collections:
  mask.resize(ElPt->size());
  makeFilterMask(&ZZ2l2vPruner::filterEl, mask);
  filter(ElPt, mask);
  filter(ElEta, mask);
  filter(ElEtaSc, mask);
  filter(ElPhi, mask);
  filter(ElE, mask);
  filter(ElId, mask);
  filter(ElCh, mask);
  filter(ElMvaTrig, mask);
  filter(ElMvaNonTrig, mask);
  filter(ElMvaPresel, mask);
  filter(ElDEtaTkScAtVtx, mask);
  filter(ElDPhiTkScAtVtx, mask);
  filter(ElHoE, mask);
  filter(ElSigmaIetaIeta, mask);
  filter(ElSigmaIetaIetaFull5x5, mask);
  filter(ElEinvMinusPinv, mask);
  filter(ElD0, mask);
  filter(ElDz, mask);
  filter(ElExpectedMissingInnerHitCnt, mask);
  filter(ElPassConvVeto, mask);
  filter(ElHltMatch, mask);
  filter(ElPfIsoChHad, mask);
  filter(ElPfIsoNeutralHad, mask);
  filter(ElPfIsoIso, mask);
  filter(ElPfIsoPuChHad, mask);
  filter(ElPfIsoRaw, mask);
  filter(ElPfIsoDbeta, mask);
  filter(ElPfIsoRho, mask);
  filter(ElAEff, mask);
}


//to be run after skimCollections
bool ZZ2l2vPruner::eventSelection(){
  if(!ZZ2l2vPruner::passAnyTrigger()) return false;
  switch(iSubSelection_){
  case DMu:
    return MuPt->size() > 1;
  case DE:
    return ElPt->size() > 1;
  case NSubSels:
  default:
    return false;
  }
};

bool ZZ2l2vPruner::filterMu(int iMu){
  return ((*MuPt)[iMu] > minLepPt);
}

bool ZZ2l2vPruner::filterEl(int iEl){
  return ((*ElPt)[iEl] > minLepPt);
}

bool ZZ2l2vPruner::passAnyTrigger(){ //Used for MC, which are required to pass any trigger of the analysis.
  vector<vector<int> > trigList(Ntrig);
  trigList[DoubleMu].insert(trigList[DoubleMu].end(),trigDoubleMu,trigDoubleMu+(sizeof(trigDoubleMu)/sizeof(trigDoubleMu[0])));
  trigList[SingleMu].insert(trigList[SingleMu].end(),trigSingleMu,trigSingleMu+(sizeof(trigSingleMu)/sizeof(trigSingleMu[0])));
  trigList[DoubleE].insert(trigList[DoubleE].end(),trigDoubleE,trigDoubleE+(sizeof(trigDoubleE)/sizeof(trigDoubleE[0])));
  //trigList[HighPtE].insert(trigList[HighPtE].end(),{}); //No High-pT E trigger available
  trigList[SingleE].insert(trigList[SingleE].end(),trigSingleE,trigSingleE+(sizeof(trigSingleE)/sizeof(trigSingleE[0])));
  trigList[EMu].insert(trigList[EMu].end(),trigEMu,trigEMu+(sizeof(trigEMu)/sizeof(trigEMu[0])));
  trigList[SinglePhoton].insert(trigList[SinglePhoton].end(),trigSinglePhoton,trigSinglePhoton+(sizeof(trigSinglePhoton)/sizeof(trigSinglePhoton[0])));
  for(unsigned int i = 0 ; i < trigList[DoubleMu].size() ; i++)  if(TrigHltDiMu & (1<<trigList.at(DoubleMu).at(i))) return true;
  for(unsigned int i = 0 ; i < trigList[SingleMu].size() ; i++)  if(TrigHltMu & (1<<trigList.at(SingleMu).at(i))) return true;
  for(unsigned int i = 0 ; i < trigList[DoubleE].size() ; i++)  if(TrigHltDiEl & (1<<trigList.at(DoubleE).at(i))) return true;
  for(unsigned int i = 0 ; i < trigList[SingleE].size() ; i++)  if(TrigHltEl & (1<<trigList.at(SingleE).at(i))) return true;
  for(unsigned int i = 0 ; i < trigList[EMu].size() ; i++)  if(TrigHltElMu & (1<<trigList.at(EMu).at(i))) return true;
  for(unsigned int i = 0 ; i < trigList[SinglePhoton].size() ; i++)  if(TrigHltPhot & (1<<trigList.at(SinglePhoton).at(i))) return true;
  return false;
}
