# This is the configuration file for e-mu method for the DY analysis, year 2016.
# Please keep it organized, and don't delete comments.

# Options related to output and logs
log:
    # Whether to use colors in the terminal.
    #Possible values: yes|no|auto (default: auto)
    color: auto

    # Controls what's printed to the screen.
    # Possible values: debug|info|warn|error|fatal (default: info)
    log level: info

    # Pipe logs to the given log file, comment out for no log.
    log file: log16_preAPV_emu_method.txt

    # Controls what's written in the log file.
    # Possible values: debug|info|warn|error|fatal (default: debug)
    log file level: debug

    # Whether to override ROOT's default log handler.
    # Default value: yes
    #override root handler: yes

# Dilepton file location
ll location: MuMu_2016preAPV

# emu file location
emu location: EMu_2016preAPV

# Whether results are preliminary (for plots)
preliminary: yes

# List of available data/MC samples
samples:
    ### DATA
    - name: data
      type: data
      jobs: 16
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_SingleMuon_data.txt
    ### MC
    # - name: DYJets
    #   type: MC
    #   jobs: 20
    #   nano dir: Catalogs/2016preAPV
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu.txt
    # - name: DYJets_M-10to50
    #   type: MC
    #   jobs: 2
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-10to50.txt
    # - name: DYJets_M-50to100
    #   type: MC
    #   jobs: 50
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-50to100.txt
    # - name: DYJets_M-100to200
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-100to200.txt
    # - name: DYJets_M-200to400
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-200to400.txt
    # - name: DYJets_M-400to500
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-400to500.txt
    # - name: DYJets_M-500to700
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-500to700.txt
    # - name: DYJets_M-700to800
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-700to800.txt
    # - name: DYJets_M-800to1000
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-800to1000.txt
    # - name: DYJets_M-1000to1500
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-1000to1500.txt
    # - name: DYJets_M-1500to2000
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-1500to2000.txt
    # - name: DYJets_M-2000toInf
    #   type: MC
    #   nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
    #   catalog: Catalog2016_bonzai_DYJetsToMuMu_M-2000toInf.txt
    ### BACKGROUND
    - name: ST_s-channel
      type: background
      nano dir: Catalogs/2016preAPV/
      catalog: Catalog2016_bonzai_ST_s-channel.txt
    - name: ST_t-channel_antitop
      type: background
      nano dir: Catalogs/2016preAPV/
      catalog: Catalog2016_bonzai_ST_t-channel_antitop.txt
    - name: ST_t-channel_top
      type: background
      jobs: 3
      nano dir: Catalogs/2016preAPV/
      catalog: Catalog2016_bonzai_ST_t-channel_top.txt
    - name: ST_tW_antitop
      type: background
      nano dir: Catalogs/2016preAPV/
      catalog: Catalog2016_bonzai_ST_tW_antitop.txt
    - name: ST_tW_top
      type: background
      nano dir: Catalogs/2016preAPV/
      catalog: Catalog2016_bonzai_ST_tW_top.txt
    # - name: WJetsToLNu
    #   type: background
    #   jobs: 4
    #   nano dir: Catalogs/2016preAPV/
    #   catalog: Catalog2016_bonzai_WJetsToLNu.txt
    - name: WWTo2L2Nu
      type: background
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_WWTo2L2Nu.txt
    - name: WZ
      type: background
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_WZ.txt
    - name: ZZ
      type: background
      jobs: 5
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_ZZ.txt
    - name: TT
      type: background
      jobs: 10
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_TTTo2L2Nu.txt
    - name: TauTau
      type: background
      jobs: 3
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_TauTau.txt
    - name: GammaGamma
      type: background
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_GGToLL.txt
    - name: GammaGamma_M-5to50
      type: background
      nano dir: Catalogs/2016preAPV/MassBinned_MiNNLO
      catalog: Catalog2016_bonzai_GGToLL_M-5to50.txt
    - name: Fakes
      type: background
      nano dir: Catalogs/2016preAPV
      catalog: Catalog2016_bonzai_SingleMuon_data.txt

MC grouping:
    - legend: "t#bar{t}"
      samples: [ TT ]
      color: 600 # kBlue
    - legend: "DY #rightarrow #tau#tau"
      samples: [ TauTau ]
      color: 434 # kCyan + 2
    - legend: ZZ
      samples: [ ZZ ]
      color: 633 # kRed + 1
    - legend: WW
      samples: [ WWTo2L2Nu ]
      color: 634 # kRed + 2
    - legend: WZ
      samples: [ WZ ]
      color: 633 # kRed + 1
    - legend: Single top
      samples: [ ST_s-channel, ST_t-channel_antitop, ST_t-channel_top, ST_tW_antitop, ST_tW_top ]
      color: 616 # kMagenta
    - legend: "#gamma#gamma"
      samples: [ GammaGamma, GammaGamma_M-5to50 ]
      color: 800 # kOrange
    - legend: "Fakes"
      samples: [ Fakes ]
      color: 803 # kOrange+3
    
plots:
    - selector: '^.*'
      produce: no
    - selector: 'el.*_inc0jet'
      produce: yes
    - selector: 'mu.*_inc0jet'
      produce: yes
    - selector: '.*leading.*'
      produce: no
    - selector: 'mass_wide_range_inc0jet'
      produce: yes
    - selector: 'mass_inc0jet'
      produce: yes
    - selector: 'nvtx_inc0jet'
      produce: yes
    - selector: 'phistar_inc0jet'
      produce: yes
    - selector: 'pt_inc0jet.*'
      produce: yes
    - selector: 'rapidity_inc0jet.*'
      produce: yes
    - selector: 'mll_over_ptsub_inc0jet'
      produce: yes
    - selector: 'MET_pt_inc0jet'
      produce: yes
    - selector: 'MT_inc0jet'
      produce: yes
    - selector: '.*gen.*'
      produce: no
    - selector: '.*matrix.*'
      produce: no
    - selector: '.*UF.*'
      produce: no
    - selector: '.*OF.*'
      produce: no
    - selector: '.*zoom.*'
      produce: no
    # Style changes
    - selector: '.*'
#      ratio min: 0.601
#      ratio max: 1.399
      ratio min: 0.801
      ratio max: 1.199
    - selector: '^phistar.*'
      log x: yes
    - selector: '^pt.*'
      log x: yes
    - selector: '^pt_cut.*'
      log x: yes
    - selector: '^mass_wide.*'
      log x: yes
    - selector: 'mass_inc0jet'
      ratio min: 0.801
      ratio max: 1.199
    # Axis labels
    - selector: '^mass.*'
      x axis label: 'M_{#mu#mu}'
      x axis unit: 'GeV'
    - selector: '^nJets.*'
      x axis label: 'Exclusive number of jets'
    - selector: '^nJetsIncl.*'
      x axis label: 'Inclusive number of jets'
    - selector: '^phistar.*'
      x axis label: '#phi*'
    - selector: '^pt.*'
      x axis label: 'p_{T}^{#mu#mu}'
      x axis unit: 'GeV'
    - selector: '.+mass(.*)_(.*).*'
      x axis detail: '$1 #leq M_{#mu#mu} < $2 GeV'
    - selector: '.*inc(1|2)jet.*'
      x axis detail: 'N_{jets} #geq $1'
    - selector: '.*exc(1|2)jet.*'
      x axis detail: 'N_{jets} = $1'
    - selector: '^mass_cut.*'
      x axis label: 'M_{#mu#mu}'
      x axis unit: 'GeV'
    - selector: '^pt_cut.*'
      x axis label: 'p_{T}^{#mu#mu}'
      x axis unit: 'GeV'